### ISSUE TITLE
replacing one (empty) bag w/ another results in the inventory not being usable

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/unified_inventory#208]
you can look inside the new bag, but you can't put anything inside it.

**Comment by eshattow** [comment]
I found that once a bag item is set to a bag slot i.e. Bag 1, clicking that bag item to grab it and click i.e. "Bag 1" button then placing within its own inventory the bag disappears completely. Not sure if that is an old bug or related to this.

**Comment by SmallJoker** [comment]
@eshattow That's a different issue. Fixed in 177debd.

**Comment by SmallJoker** [comment]
@fluxionary This seems to be fixed on my end. Could you please try to reproduce this?

**Comment by fluxionary** [comment]
> @fluxionary This seems to be fixed on my end. Could you please try to reproduce this?

i still have the issue. i'm testing w/ the most recent unified_inventory (https://github.com/minetest-mods/unified_inventory/commit/d6d4bea819fe44ef447491834ef25a834a575bc2) and the most recent minetest (https://github.com/minetest/minetest/commit/531122ee8681d9de7b38879563da4cdcc71bfe44). i get the following warning in my console:

```
2023-06-20 11:04:32: WARNING[Main]: GUIInventoryList::draw(): The inventory list "bag3contents" @ "current_player" doesn't exist
```

**Comment by fluxionary** [comment]
the engine issue got fixed. testing with the most recent build, i can't replicate the issue.
